const data = {
  labels: ['January', 'February', 'March', 'April', 'May', 'June', 'July'],
  datasets: [
    {
      label: 'My First dataset',
      backgroundColor: 'rgba(255,99,132,0.2)',
      borderColor: 'rgba(255,99,132,1)',
      borderWidth: 1,
      hoverBackgroundColor: 'rgba(255,99,132,0.4)',
      hoverBorderColor: 'rgba(255,99,132,1)',
      data: [65, 59, 80, 81, 56, 55, 40],
    },
  ],
};

const data2 = {
  labels: ['ÁREA CENTRAL',
  'CEBIOGEN',
  'CECYT NO. 01',
  'CECYT NO. 02',
  'CECYT NO. 03',
  'CECYT NO. 04',
  'CECYT NO. 07',
  'CECYT NO. 08',
  'CECYT NO. 09',
  'CECYT NO. 10',
  'CECYT NO. 11',
  'CECYT NO. 13',
  'CECYT NO. 15',
  'CECyT No. 16',
  'CECYT NO. 18',
  'CEPROBI',
  'CET NO. 1',
  'CIBA TLAX.',
  'CIC',
  'CICATA ALT.',
  'CICATA LEG.',
  'CICATA QRO.',
  'CICIMAR',
  'CICS M.A.',
  'CICS S.T.',
  'CIDETEC',
  'CIECAS',
  'CIIDIR DGO.',
  'CIIDIR MICH.',
  'CIIDIR OAX.',
  'CIIDIR SIN.',
  'CIIEMAD',
  'CIITEC AZC.',
  'CITEDI',
  'CMPL',
  'CNMN',
  'DECANATO',
  'DFIE',
  'ENCB',
  'ENMH',
  'ESCA S.T.',
  'ESCA TEP.',
  'ESCOM',
  'ESE',
  'ESEO',
  'ESFM',
  'ESIA TEC.',
  'ESIA TIC.',
  'ESIA ZAC.',
  'ESIME AZC.',
  'ESIME CUL.',
  'ESIME TIC.',
  'ESIME ZAC.',
  'ESIQIE',
  'ESIT',
  'ESM',
  'EST',
  'SIP',
  'UPIBI',
  'UPIEM',
  'UPII GTO.',
  'UPII ZAC.',
  'UPIICSA',
  'UPIIH',
  'UPIITA'],
  datasets: [
    {
      label: 'Total',
      backgroundColor: 'rgba(255,0,0)',
      borderColor: 'rgba(227,0,0)',
      borderWidth: 1,
      hoverBackgroundColor: 'rgba(255,99,132,0.4)',
      hoverBorderColor: 'rgba(255,99,132,1)',
      data: [20,
        42,
        7,
        40,
        10,
        1,
        20,
        5,
        5,
        1,
        10,
        8,
        3,
        7,
        16,
        58,
        1,
        55,
        98,
        12,
        72,
        41,
        105,
        5,
        3,
        50,
        37,
        45,
        22,
        77,
        65,
        49,
        24,
        19,
        20,
        19,
        4,
        2,
        330,
        36,
        33,
        15,
        48,
        47,
        3,
        70,
        40,
        9,
        9,
        47,
        99,
        37,
        132,
        113,
        3,
        202,
        15,
        4,
        82,
        12,
        32,
        39,
        44,
        42,
        79],
    },
  ],
};

const barSettings = {
  height: 350,
};

export { data, barSettings, data2 };
